<Project>
  <PropertyGroup>
    <CodesignKey>iPhone Developer</CodesignKey>
    <NullabilityInfoContextSupport>true</NullabilityInfoContextSupport>
    <!-- MT7091 occurs when referencing a .framework bundle that consists of a static library.
         It only warns about not copying the library to the app bundle to save space,
         so there's nothing to be worried about. -->
    <NoWarn>$(NoWarn);MT7091</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <!-- On debug configurations, we use Mono interpreter for faster compilation. -->
    <UseInterpreter>true</UseInterpreter>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <!-- On release configurations, we use AOT compiler for optimal performance. -->
    <UseInterpreter>false</UseInterpreter>
  </PropertyGroup>
  <ItemGroup>
    <NativeReference Include="$(MSBuildThisFileDirectory)osu.Framework.iOS\runtimes\ios\native\bass.xcframework" Kind="Framework" SmartLink="false" ForceLoad="true" />
    <NativeReference Include="$(MSBuildThisFileDirectory)osu.Framework.iOS\runtimes\ios\native\bass_fx.xcframework" Kind="Framework" SmartLink="false" ForceLoad="true" />
    <NativeReference Include="$(MSBuildThisFileDirectory)osu.Framework.iOS\runtimes\ios\native\bassmix.xcframework" Kind="Framework" SmartLink="false" ForceLoad="true" />
    <NativeReference Include="$(MSBuildThisFileDirectory)osu.Framework.iOS\runtimes\ios\native\libavcodec.xcframework" Kind="Framework" SmartLink="false" ForceLoad="true" />
    <NativeReference Include="$(MSBuildThisFileDirectory)osu.Framework.iOS\runtimes\ios\native\libavdevice.xcframework" Kind="Framework" SmartLink="false" ForceLoad="true" />
    <NativeReference Include="$(MSBuildThisFileDirectory)osu.Framework.iOS\runtimes\ios\native\libavformat.xcframework" Kind="Framework" SmartLink="false" ForceLoad="true" />
    <NativeReference Include="$(MSBuildThisFileDirectory)osu.Framework.iOS\runtimes\ios\native\libavutil.xcframework" Kind="Framework" SmartLink="false" ForceLoad="true" />
    <NativeReference Include="$(MSBuildThisFileDirectory)osu.Framework.iOS\runtimes\ios\native\libswresample.xcframework" Kind="Framework" SmartLink="false" ForceLoad="true" />
    <NativeReference Include="$(MSBuildThisFileDirectory)osu.Framework.iOS\runtimes\ios\native\libswscale.xcframework" Kind="Framework" SmartLink="false" ForceLoad="true" />
    <NativeReference Include="$(MSBuildThisFileDirectory)osu.Framework.iOS\runtimes\ios\native\metal-mono-workaround.xcframework" Kind="Framework" SmartLink="false" ForceLoad="true" />
  </ItemGroup>

  <!-- Some transitive assemblies don't behave well with AOT, so we strip them.
       Importantly, this is done in such a way that the assembly's MVID is preserved to satisfy runtime requirements. -->
  <Target Name="OsuFrameworkIOSStripAssemblies" AfterTargets="ILLink" BeforeTargets="_AOTCompile">
    <PropertyGroup>
      <AssemblyStripper>$(MSBuildThisFileDirectory)tools\AssemblyStripper.cs</AssemblyStripper>
      <LinkedOutputFolder>$(IntermediateOutputPath)linked\</LinkedOutputFolder>
    </PropertyGroup>
    <ItemGroup>
      <AssembliesToStrip Include="SharpGen.Runtime.dll"/>
      <AssembliesToStrip Include="SharpGen.Runtime.COM.dll"/>
      <AssembliesToStrip Include="Vortice.D3DCompiler.dll"/>
      <AssembliesToStrip Include="Vortice.Direct3D11.dll"/>
      <AssembliesToStrip Include="Vortice.DirectX.dll"/>
      <AssembliesToStrip Include="Vortice.DXGI.dll"/>
    </ItemGroup>
    <Exec WorkingDirectory="$(LinkedOutputFolder)" Command="dotnet &quot;$(AssemblyStripper)&quot; -- @(AssembliesToStrip, ' ')"/>
  </Target>

  <!-- OpenTabletDriver contains P/Invokes to the "Quartz" framework for native macOS code.
       This leads iOS linker into attempting to include that framework, despite not existing on such platform.
       See: https://github.com/OpenTabletDriver/OpenTabletDriver/issues/2524 / https://github.com/xamarin/xamarin-macios/issues/15118#issuecomment-1141893683 -->
  <!-- There's also P/Invokes for "ApplicationServices" framework somewhere in the referenced libraries... -->
  <Target Name="OsuFrameworkIOSRemoveMacOSFrameworks" BeforeTargets="_ComputeLinkNativeExecutableInputs" AfterTargets="_LoadLinkerOutput">
    <ItemGroup>
      <_LinkerFrameworks Remove="Quartz"/>
      <_LinkerFrameworks Remove="ApplicationServices"/>
    </ItemGroup>
  </Target>
</Project>
