// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
// See the LICENCE file in the repository root for full licence text.

#nullable disable

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using osu.Framework.Development;
using osu.Framework.Extensions.TypeExtensions;
using osu.Framework.Logging;

namespace osu.Framework.IO.Stores
{
    public interface IResourceStore<T> : IDisposable
        where T : class
    {
        /// <summary>
        /// Retrieves an object from the store.
        /// </summary>
        /// <param name="name">The name of the object.</param>
        /// <returns>The object.</returns>
        T Get(string name);

        /// <summary>
        /// Retrieves an object from the store asynchronously.
        /// </summary>
        /// <param name="name">The name of the object.</param>
        /// <param name="cancellationToken">A cancellation token.</param>
        /// <returns>The object.</returns>
        Task<T> GetAsync(string name, CancellationToken cancellationToken = default);

        Stream GetStream(string name);

        /// <summary>
        /// Gets a collection of string representations of the resources available in this store.
        /// </summary>
        /// <returns>String representations of the resources available.</returns>
        IEnumerable<string> GetAvailableResources();
    }

    public static class ResourceStoreExtensions
    {
        /// <summary>
        /// List of substrings that indicate a file should generally be ignored as noise
        /// (usually due to representing no useful data and being autogenerated by the OS).
        /// </summary>
        private static readonly string[] system_filename_ignore_list =
        {
            // Mac-specific
            "__MACOSX",
            ".DS_Store",
            // Windows-specific
            "Thumbs.db"
        };

        /// <summary>
        /// Outputs a message to the log if a resource was not retrieved on a non-background thread.
        /// </summary>
        /// <param name="store">The store which the resources was retrieved from.</param>
        /// <param name="resourceName">The resource retrieved.</param>
        internal static void LogIfNonBackgroundThread<T>(this IResourceStore<T> store, string resourceName)
            where T : class
        {
            if (!DebugUtils.LogPerformanceIssues)
                return;

            if (ThreadSafety.IsUpdateThread || ThreadSafety.IsDrawThread || ThreadSafety.IsAudioThread)
            {
                Logger.Log($"Resource {resourceName} was retrieved from a {store.GetType().ReadableName()} on a non-background thread.", LoggingTarget.Performance);
                Logger.Log(new StackTrace(1).ToString(), LoggingTarget.Performance, outputToListeners: false);
            }
        }

        /// <summary>
        /// Remove common noise filenames generated by OS / host systems.
        /// </summary>
        /// <param name="source">A list of filenames.</param>
        /// <returns>A list of filenames excluding common system files.</returns>
        public static IEnumerable<string> ExcludeSystemFileNames(this IEnumerable<string> source) =>
            source.Where(entry => !system_filename_ignore_list.Any(ignoredName => entry.Contains(ignoredName, StringComparison.OrdinalIgnoreCase)));
    }
}
